# Generated by Django 3.2.7 on 2021-10-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.CharField(max_length=50000)),
                ('user_2', models.CharField(max_length=50000)),
                ('chat_link_name', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
