# Generated by Django 3.2.7 on 2021-10-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to', models.CharField(max_length=500)),
                ('send_from', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=5000)),
            ],
        ),
    ]
