# Generated by Django 3.2.7 on 2021-10-03 02:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register_app', '0003_auto_20211003_0356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='UserInfo',
        ),
    ]
