# Generated by Django 3.2.7 on 2021-10-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0004_rename_register_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='friends',
            field=models.IntegerField(null=True),
        ),
    ]
