# Generated by Django 3.2.7 on 2021-10-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0009_auto_20211003_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.CharField(max_length=5000),
        ),
    ]
