# Generated by Django 3.2.7 on 2021-10-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0010_alter_userinfo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
    ]
