# Generated by Django 3.2.7 on 2021-10-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0011_alter_userinfo_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='following',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
